@startuml my first uml

actor user
participant backend
database dataStore

user -> backend: Send Http request to get info
backend -> dataStore: Check in DB
dataStore -> backend: Success Response
backend -> user: Show user detail

@enduml
