@startuml statechart
title Состояния заявки

[*] --> Новая : пользователь создал заявку
Новая --> Согласуется : эксперт ответил на заявку \n и предложил время
Согласуется --> Согласована : пользователь \n согласовал заявку
Согласуется --> Новая : пользователь отказался \n согласовывать заявку
Согласована --> Выполнена : консультация состоялась
Выполнена --> [*] 

Новая --> Отменена : пользователь \n отменил заявку
Согласуется --> Отменена : пользователь \n отменил заявку
Согласована --> Отменена : пользователь \n отменил заявку
Отменена --> [*]

Новая --> Проблемная : [Время с момента \n создания > недели]
Согласуется --> Проблемная : [Прошло время \n предложенное экспертом]
Проблемная --> Отменена : Заявка отменена \n пользователем или администратором
Проблемная --> Согласуется : Администратор \n назначил эксперта

@enduml